---
apiVersion: v1
kind: ReplicationController
metadata:
  name: todowebapp-api
  namespace: todoapp
  labels:
    app: todowebapp-api
spec:
  replicas: 1
  selector:
    app: todowebapp-api
  template:
    metadata:
      labels:
        app: todowebapp-api
    spec:
      containers:
        - name: todowebapp-api
          image: rizalachp/todowebapp-api:release
          ports:
            - containerPort: 3000
              name: api-server
---
apiVersion: v1
kind: Service
metadata:
  name: todowebapp-api
  namespace: todoapp
  labels:
    app: todowebapp-api
spec:
  ports:
    - port: 3000
      targetPort: api-server
  selector:
    app: todowebapp-api
---
